apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}    
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
        - image: eromski/solar-system:1-28dac3c4b3ec1008d2cb8a85b7fdedfdc488535f
          name: solar-system
          imagePullPolicy: Always
          ports:
            - containerPort: 80 
    
