# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}    
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
        - image: eromski/solar-system:21-6ec3071f861a5cc882055b2693985f9709c04580
          name: solar-system
          imagePullPolicy: Always
          ports:
            - containerPort: 80 
    
